-- =====================================================================
-- 0027 - Draghi: caratteri piu' ricchi, ispirati ai draghi di Game of
-- Thrones e di Fuoco e Sangue
-- Eseguire in Supabase: SQL Editor -> New query -> incolla -> Run
--
-- Ogni carattere ha un titolo e una descrizione ("Titolo — descrizione"):
-- come si comporta con il cavaliere, con gli altri draghi, in battaglia,
-- e uno spunto per giocarlo. I draghi gia' esistenti tengono il loro
-- carattere; i nuovi pescano da questo elenco.
-- =====================================================================

delete from public.dragon_temperaments;

insert into public.dragon_temperaments (text) values
('Il Terrore Nero (sull''esempio di Balerion) — Antico nello sguardo anche quando è giovane, si muove con la calma di chi sa di essere il più forte. Non ha bisogno di ruggire per farsi obbedire: gli altri draghi abbassano il capo al suo passaggio. Con il cavaliere è esigente e silenzioso, concede fiducia solo a chi dimostra di non temerlo. In battaglia è paziente, aspetta il momento giusto e poi colpisce con un fuoco che non lascia nulla in piedi. Spunto: la sua sola presenza cambia l''umore di una corte; gli uomini lo temono, i rivali lo invidiano.'),
('La Vecchia Regina (sull''esempio di Vhagar) — Lenta, pesante, con una memoria lunghissima: ricorda ogni ferita e ogni torto, anche dopo anni. Disprezza i draghi giovani e chiassosi e non tollera di essere sfidata. Cambiare cavaliere per lei è un lutto, e chi la monta deve guadagnarsi ogni giorno la sua pazienza. In guerra è inarrestabile e spietata, non conosce pietà per uomini né draghi. Spunto: un''ombra del passato del suo vecchio cavaliere la tormenta ancora.'),
('La Regina Fiera (sull''esempio di Meraxes) — Orgogliosa, impetuosa, combattiva: vola davanti a tutti e odia restare indietro. Ha un temperamento caldo che si accende in un istante e si ama solo da vicino. Con il cavaliere ha un legame passionale fatto di slanci e litigi. In battaglia è audace fino alla temerarietà e non indietreggia mai, anche davanti a ciò che dovrebbe temere. Spunto: il suo orgoglio la spinge in imprese che un drago più prudente eviterebbe.'),
('Il Wyrm di Sangue (sull''esempio di Caraxes) — Snello, rosso come una ferita e dal grido stridulo che gela il sangue. Vive per la caccia e per la lotta, e nella quiete si annoia profondamente. È legato al cavaliere in modo totale, quasi feroce, e ne rispecchia gli sbalzi d''umore. In combattimento è rapido, crudele e imprevedibile, ama ghermire e strappare più che bruciare da lontano. Spunto: dove passa lascia storie di paura, e qualcuno ne cerca vendetta.'),
('La Viziata (sull''esempio di Syrax) — Abituata alle comodità, al cibo migliore e alle carezze, considera il suo nido una reggia. È affettuosa e protettiva con il suo cavaliere, ma pigra negli addestramenti. Ha poca esperienza di guerra e la affronta con più rabbia che tecnica. Diventa però una furia se qualcuno minaccia ciò che considera suo. Spunto: la sua pigrizia potrebbe costare cara proprio nel momento in cui servirà davvero.'),
('La Regina Rossa (sull''esempio di Meleys) — Velocissima e ardita, la più rapida tra i draghi della sua generazione. Ama le acrobazie e le picchiate improvvise, e adora mettersi in mostra. Con il cavaliere ha un rapporto di complicità e sfida reciproca. In battaglia attacca senza esitazione anche avversari molto più grandi di lei, fidandosi della sua velocità. Spunto: non rifiuta mai una sfida, e questo la rende tanto ammirata quanto vulnerabile.'),
('La Furia di Bronzo (sull''esempio di Vermithor) — Enorme e possente, ha il passo pesante e la voce come un tuono lontano. Solitario e schivo, si lega a fatica e ricorda a lungo chi lo ha abbandonato. Quando si fida, però, è un compagno saldo come una montagna. In guerra è una forza della natura, lento a muoversi ma devastante quando colpisce. Spunto: porta il ricordo di un cavaliere perduto e mette alla prova chiunque provi a sostituirlo.'),
('Ala d''Argento (sull''esempio di Silverwing) — Gentile e mite, si lascia avvicinare anche dagli estranei e tollera i bambini. È il drago più docile della casata, quello che non spaventa nessuno. Con il cavaliere è affettuosa e obbediente. In battaglia, però, sa essere sorprendentemente feroce quando viene provocata o quando vede minacciato chi ama. Spunto: la sua mitezza la rende preziosa per la diplomazia, e qualcuno potrebbe scambiarla per debolezza.'),
('Fuoco di Sogno (sull''esempio di Dreamfyre) — Snella, elegante e intelligente, osserva tutto con occhi attenti. Ama i luoghi alti e nascosti, e ha un istinto materno fortissimo: veglia sulle uova della casata come fossero sue. Con il cavaliere è riservata ma leale. In battaglia preferisce difendere che attaccare, ed è terribile quando protegge il suo nido. Spunto: sa dove si trovano uova che altri credono perdute.'),
('Il Fumo di Mare (sull''esempio di Seasmoke) — Inquieto e malinconico, passa ore a volare sopra il mare come se cercasse qualcosa. Non sopporta di stare fermo e soffre la solitudine. Si affeziona in fretta, ma a modo suo: sceglie lui il cavaliere, non il contrario. In battaglia è agile e imprevedibile, più adatto alle schermaglie che agli scontri frontali. Spunto: potrebbe lasciarsi avvicinare da qualcuno di inatteso, senza sangue nobile.'),
('Il Dorato (sull''esempio di Sunfyre) — Splendido come oro fuso al sole, è considerato il drago più bello dei Sette Regni e lo sa. Vanitoso, ama essere guardato, ma è di una lealtà assoluta verso il suo cavaliere. Non lo abbandona mai, nemmeno ferito, nemmeno sconfitto. In battaglia combatte con un coraggio ostinato che sfida ogni ragione. Spunto: la sua fedeltà incrollabile ispira canzoni, e qualcuno vorrebbe spezzarla.'),
('La Regina Blu (sull''esempio di Tessarion) — Giovane, vivace e fiera, ha scaglie che brillano di cobalto e un carattere pieno di energia. Ama le gare e non sopporta di essere considerata una novellina. Con il cavaliere è entusiasta e un po'' impaziente. In battaglia è audace e rapida, ma ancora inesperta. Spunto: vuole a tutti i costi dimostrare il suo valore, anche quando sarebbe meglio aspettare.'),
('La Danzatrice (sull''esempio di Moondancer) — Piccola, leggera e agilissima, danza nell''aria come una foglia nel vento. Compensa la taglia con la rapidità e un coraggio sproporzionato. Con il cavaliere ha un rapporto tenero e giocoso. In battaglia evita gli scontri frontali e punta agli occhi e alle ali degli avversari più grandi. Spunto: tutti la sottovalutano, ed è proprio questo il suo vantaggio.'),
('Il Giovane Ribelle (sull''esempio di Arrax) — Giovane e impetuoso, ha ancora molto da imparare e lo sa poco. Si spaventa per i temporali e si innervosisce davanti ai draghi più grandi. Obbedisce al cavaliere quando è tranquillo, ma nella tensione può fare di testa sua. In battaglia è pericoloso più per l''imprevedibilità che per la forza. Spunto: un incidente causato dalla sua disobbedienza potrebbe avere conseguenze politiche.'),
('L''Esploratore (sull''esempio di Vermax) — Curioso e avventato, si infila nelle grotte, tra le rovine e nei vulcani spenti. Lascia nidi e tane un po'' ovunque, e torna spesso con prede di luoghi lontani. Con il cavaliere è complice di ogni avventura. In battaglia è coraggioso ma distratto. Spunto: in una delle sue esplorazioni ha trovato qualcosa che non doveva vedere.'),
('Il Ladro di Pecore (sull''esempio di Sheepstealer) — Selvatico e diffidente, cresciuto lontano dagli uomini, si è abituato a rubare il bestiame dei pastori. Non si fida di nessuno e si conquista solo con pazienza e cibo. Una volta legato, però, è fedele in modo sorprendente. In battaglia è astuto, preferisce l''agguato allo scontro aperto. Spunto: nei villaggi vicini c''è ancora chi lo maledice per le greggi perdute.'),
('Il Cannibale (sull''esempio di Cannibal) — Feroce, oscuro e mai veramente domato. Divora le prede in modo brutale e guarda con fame persino le uova e i draghi più piccoli. Nessuno si avvicina al suo nido senza paura. Il legame con il cavaliere è fragile, una tregua più che un''amicizia. In battaglia è una belva senza regole. Spunto: la casata deve tenerlo lontano dalle uova, e non sempre ci riesce.'),
('Il Fantasma Grigio (sull''esempio di Grey Ghost) — Timido e schivo, color nebbia, evita gli uomini e caccia pesci tra gli scogli. Si muove in silenzio e scompare tra le nuvole basse. Con il cavaliere è riservato, quasi invisibile, ma attento. In battaglia preferisce non esserci: se costretto, attacca dall''alto e svanisce. Spunto: la sua discrezione lo rende perfetto per missioni che nessuno deve notare.'),
('L''Indomabile (sull''esempio di Drogon) — Ribelle e amante della libertà, non sopporta catene né recinti. Si allontana per giorni e torna quando vuole. Riconosce un solo padrone, e anche a lui obbedisce solo quando ne condivide il volere. In battaglia è una tempesta di fuoco nero e furia. Spunto: tenerlo in una fossa o in una stalla è un rischio; lasciarlo libero lo è altrettanto.'),
('Il Verde Rancoroso (sull''esempio di Rhaegal) — Generalmente tranquillo, ma porta un rancore profondo verso chi lo ha imprigionato o umiliato. Non dimentica i luoghi in cui ha sofferto. Con il cavaliere è più docile di molti suoi simili, se trattato con rispetto. In battaglia diventa crudele quando riconosce un nemico del passato. Spunto: c''è qualcuno, alla corte o tra i servi, che lui riconosce e odia.'),
('Il Pallido (sull''esempio di Viserion) — Chiaro di scaglie e mite d''animo, si lascia guidare più facilmente degli altri. È curioso e cerca la compagnia degli uomini. Con il cavaliere è affettuoso e attento. In battaglia è affidabile ma non brilla per ferocia. Spunto: la sua indole gentile lo rende vulnerabile a chi volesse ingannarlo o portarlo via.'),
('L''Alba (sull''esempio di Morning) — Giovane e aggraziata, con scaglie dalle tinte del cielo al mattino. È allegra, socievole e ama la luce e le altezze. Con il cavaliere è dolce e piena di entusiasmo. In battaglia è ancora inesperta e va protetta. Spunto: rappresenta il futuro della casata, e proprio per questo fa gola a molti.'),
('La Nube di Tempesta (sull''esempio di Stormcloud) — Giovanissimo e ancora fragile, è nato in un momento difficile e ne porta i segni. Spaventato dal fragore della guerra, trova il coraggio solo accanto al suo cavaliere. Con lui ha un legame tenerissimo. In battaglia supera i suoi limiti per proteggerlo, anche a costo di farsi male. Spunto: il suo coraggio nasce dall''affetto, non dalla forza.'),
('Il Nervoso della Fossa (sull''esempio di Tyraxes) — Cresciuto tra le mura della Fossa del Drago, è irrequieto, sospettoso e soffre la cattività. Si agita alle grida e ai rumori della folla, e scatta al minimo movimento brusco. Con il cavaliere è più calmo, ma resta sempre teso. In battaglia è rabbioso e difficile da guidare. Spunto: un giorno di troppo in catene potrebbe farlo esplodere.'),
('L''Ombra della Fossa (sull''esempio di Shrykos e Morghul) — Giovane, aggressivo e insofferente, non ama gli uomini che lo nutrono né quelli che lo guardano. Le catene lo hanno reso diffidente e violento. Con il cavaliere ha un legame ancora incerto, da costruire giorno per giorno. In battaglia è una minaccia anche per chi gli sta vicino. Spunto: molti pensano che sia stato un errore tenerlo rinchiuso così a lungo.'),
('L''Argento Vivo (sull''esempio di Quicksilver) — Rapido, scattante, con scaglie che riflettono la luce come metallo. Non sta mai fermo e si annoia facilmente. Con il cavaliere è giocoso e impaziente, sempre pronto a partire. In battaglia è veloce ma impulsivo, perfetto per inseguire e sfiancare. Spunto: la sua irrequietezza lo porta spesso a cacciarsi nei guai.'),
('Il Figlio di Roccia del Drago — Nato tra le montagne fumanti dell''isola, ama il caldo, lo zolfo e le caverne profonde. Ha un legame quasi mistico con la terra da cui viene e soffre lontano da essa. Con il cavaliere è leale ma nostalgico. In battaglia è temibile soprattutto vicino al fuoco e alla roccia. Spunto: sente il richiamo dell''isola e a volte vi torna senza chiedere permesso.'),
('Il Reduce della Danza — Ha visto draghi morire e cieli bruciare, e porta cicatrici antiche sulle ali. È diffidente verso gli altri draghi, che considera possibili nemici. Con il cavaliere è protettivo fino all''ossessione. In battaglia è esperto e prudente, sa quando colpire e quando fuggire. Spunto: il ricordo della guerra lo rende nervoso a ogni corte e a ogni alleanza.'),
('Il Custode del Nido — Calmo, paziente, legato al luogo in cui è nato più che alle persone. Considera la casata il suo branco e ne veglia ogni membro, uomini e draghi. Con il cavaliere è un saggio compagno, più consigliere che cavalcatura. In battaglia difende, non insegue. Spunto: si rifiuta di allontanarsi troppo da casa, e questo complica ogni spedizione.'),
('Il Selvaggio di Valyria — Ha nel sangue qualcosa di antico e indomito, come i draghi dei Signori dei Draghi prima del Disastro. Ombroso, superbo, sembra guardare gli uomini dall''alto in basso. Con il cavaliere stringe un patto più che un legame. In battaglia è terribile e altero. Spunto: le vecchie lingue di Valyria sembrano calmarlo, e nessuno sa perché.');
